apiVersion: v1
kind: ServiceAccount
metadata:
  name: configure-alertmanager-operator
  namespace: openshift-monitoring
  labels:
    hive.openshift.io/managed: "true"
    olm.managed: "true"
    operators.coreos.com/configure-alertmanager-operator.openshift-monitoring: ""
